### ISSUE TITLE
Document creating a new component

### ISSUE THREAD

**Issue by pitchinvasion** [makersacademy/components#53]

**Comment by sjmog** [comment]
In short, this is:

- Get the content for the page
- Do a content architecture (i.e. draw out the abstract data chunks and put them in a sensible order)
- Wireframe how you want that content architecture to appear, using existing components where sensible.

Here is an example:

- Content for graduates page is lots of these:
Karin Nielsen
September 2014
MD at translation agency to Entrepreneur First program 
“ I am better equipped to make some initial technology decisions myself and am empowered to start building something without depending on others. The thought of outsourcing to a dev shop or freelancer always filled me with dread because I would have had no idea what bad looks like.” 	
- Content Architecture for this is:

- Student
  - Name
  - Cohort
  - Previous Job
  - New Job
  - Quote
  - Extended case study *
  - Blog *

* = sometimes these exist, sometimes they don't

**Comment by sjmog** [comment]
Then the wireframe:

![image2](https://cloud.githubusercontent.com/assets/1960230/7811588/cc4b0532-03a3-11e5-95eb-47d0375567a9.JPG)

**Comment by sjmog** [comment]
So we need to build 2 new components:

1. Full-width slider with media components inside
2. Full-width slider with some sort of modified holler blocks inside

**Comment by sjmog** [comment]
(progress towards 1. can be seen on the #40 branch)

**Comment by pitchinvasion** [comment]
cool can you create tickets for those two new components samm? Also I'll take the rest of this issue and turn it into a wiki page and get back to you

**Comment by sjmog** [comment]
Done and done (and done and done for two more, booyah). And I built one of them in #40

**Comment by sjmog** [comment]
https://github.com/makersacademy/components/wiki/Building-a-new-component-from-scratch
